name = "MassApplyPatch"
uuid = "a374f348-d733-473a-88bc-8a13261ed0c1"
version = "0.2.0"
authors = ["ITensor developers <support@itensor.org> and contributors"]

[workspace]
projects = ["benchmark", "dev", "docs", "examples", "test"]

[deps]
Git = "d7ba0133-e1db-5d97-8f8c-041e4b3a1eb2"
GitHub = "bc5e4493-9b4d-5f90-b8aa-2b2bcaad7a26"
Suppressor = "fd094767-a336-5f1f-9728-57cf17d0bbfb"
TOML = "fa267f1f-6049-4f14-aa54-33bafae1ed76"

[compat]
Git = "1.5"
GitHub = "5.12"
Suppressor = "0.2.8"
TOML = "1.0.3"
julia = "1.10"

[apps.massapplypatch]
