name = "MassApplyPatch"
uuid = "a374f348-d733-473a-88bc-8a13261ed0c1"
version = "0.1.1"
authors = ["ITensor developers <support@itensor.org> and contributors"]

[workspace]
projects = ["benchmark", "dev", "docs", "examples", "test"]

[deps]
Git = "d7ba0133-e1db-5d97-8f8c-041e4b3a1eb2"
GitHub = "bc5e4493-9b4d-5f90-b8aa-2b2bcaad7a26"

[compat]
Git = "1.5"
GitHub = "5.12"
julia = "1.10"

[apps.massapplypatch]
