[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
MassApplyPatch = "a374f348-d733-473a-88bc-8a13261ed0c1"

[sources.MassApplyPatch]
path = ".."

[compat]
Documenter = "1"
Literate = "2"
MassApplyPatch = "0.2, 0.1"
